<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header(); the_post(); $id = get_the_ID();
$types = wp_get_post_terms( $id, 'game_type', array( 'fields' => 'names' ) );
$stores = array( '_lgd_steam_url' => 'Steam', '_lgd_google_play_url' => 'Google Play', '_lgd_apple_app_store_url' => 'App Store', '_lgd_itch_url' => 'itch.io', '_lgd_official_website' => 'Official Website' );
$scores = array( '_lgd_automated_score' => 'Legend Automated Score', '_lgd_editorial_score' => 'Legend Editorial Score', '_lgd_community_score' => 'Community Score', '_lgd_external_critic_score' => 'External Critic Score', '_lgd_external_user_score' => 'External User Score', '_lgd_steam_sentiment' => 'Store Sentiment' );
$facts = array( '_lgd_developer' => 'Developer', '_lgd_publisher' => 'Publisher', '_lgd_release_date' => 'Release Date', '_lgd_last_update_date' => 'Last Update', '_lgd_current_price' => 'Current Price', '_lgd_free_type' => 'Pricing Type', '_lgd_in_app_purchases' => 'In-app Purchases', '_lgd_advertising' => 'Advertising', '_lgd_multiplayer' => 'Multiplayer', '_lgd_online_requirement' => 'Internet Requirement', '_lgd_offline_support' => 'Offline Support', '_lgd_controller_support' => 'Controller Support', '_lgd_age_rating' => 'Age Rating', '_lgd_last_verified' => 'Last Verified' );
?>
<main class="lgd-shell">
	<section class="lgd-game-hero"><div class="lgd-container lgd-game-hero-grid"><div><div class="lgd-badges"><?php foreach ( $types as $type ) : ?><span><?php echo esc_html( $type ); ?></span><?php endforeach; ?></div><h1><?php the_title(); ?></h1><p class="lgd-lead"><?php echo esc_html( get_post_meta( $id, '_lgd_short_description', true ) ?: get_the_excerpt() ); ?></p><div class="lgd-store-links"><?php foreach ( $stores as $meta => $label ) : $url = get_post_meta( $id, $meta, true ); if ( $url ) : ?><a class="lgd-button" rel="nofollow noopener" target="_blank" href="<?php echo esc_url( $url ); ?>"><?php echo esc_html( $label ); ?></a><?php endif; endforeach; ?></div></div><div class="lgd-game-image"><?php if ( has_post_thumbnail() ) { the_post_thumbnail( 'large' ); } ?></div></div></section>
	<div class="lgd-container">
		<section class="lgd-score-board" aria-label="<?php esc_attr_e( 'Separate rating types', 'legend-game-directory' ); ?>"><?php foreach ( $scores as $meta => $label ) : $value = get_post_meta( $id, $meta, true ); ?><div class="lgd-score-box"><strong><?php echo '' === (string) $value ? esc_html__( '—', 'legend-game-directory' ) : esc_html( $value ); ?></strong><span><?php echo esc_html( $label ); ?></span></div><?php endforeach; ?></section>
		<?php $confidence = get_post_meta( $id, '_lgd_confidence', true ); $missing = (array) get_post_meta( $id, '_lgd_missing_data', true ); ?><p><?php echo esc_html( sprintf( __( 'Score confidence: %s%% · %s stored sources', 'legend-game-directory' ), '' === (string) $confidence ? 0 : $confidence, get_post_meta( $id, '_lgd_source_count', true ) ) ); ?></p><?php if ( $missing ) : ?><p class="lgd-missing"><?php echo esc_html( sprintf( __( 'Missing data: %s. Missing evidence does not receive positive points.', 'legend-game-directory' ), implode( ', ', array_map( function( $item ) { return str_replace( '_', ' ', $item ); }, $missing ) ) ) ); ?></p><?php endif; ?>
		<section class="lgd-section lgd-two-col"><article class="lgd-panel"><h2><?php esc_html_e( 'Overview', 'legend-game-directory' ); ?></h2><?php the_content(); ?><?php $best = get_post_meta( $id, '_lgd_best_for', true ); if ( $best ) : ?><h3><?php esc_html_e( 'Best for', 'legend-game-directory' ); ?></h3><p><?php echo esc_html( $best ); ?></p><?php endif; ?></article><aside class="lgd-facts"><?php foreach ( $facts as $meta => $label ) : $value = get_post_meta( $id, $meta, true ); ?><div class="lgd-fact"><span><?php echo esc_html( $label ); ?></span><strong><?php echo '' === (string) $value ? esc_html__( 'Unknown', 'legend-game-directory' ) : esc_html( is_array( $value ) ? implode( ', ', $value ) : $value ); ?></strong></div><?php endforeach; ?></aside></section>
		<?php $breakdown = get_post_meta( $id, '_lgd_score_breakdown', true ); if ( is_array( $breakdown ) ) : ?><section class="lgd-section lgd-panel"><h2><?php esc_html_e( 'Automated Score Breakdown', 'legend-game-directory' ); ?></h2><?php foreach ( $breakdown as $key => $part ) : $value = isset( $part['score'] ) ? $part['score'] : null; ?><div class="lgd-breakdown-row"><span><?php echo esc_html( ucwords( str_replace( '_', ' ', $key ) ) ); ?></span><div class="lgd-bar"><i style="width:<?php echo esc_attr( null === $value ? 0 : min( 100, max( 0, $value ) ) ); ?>%"></i></div><strong><?php echo null === $value ? esc_html__( 'Missing', 'legend-game-directory' ) : esc_html( $value ); ?></strong></div><?php endforeach; ?></section><?php endif; ?>
		<section class="lgd-section lgd-two-col"><div class="lgd-panel"><h2><?php esc_html_e( 'Pros', 'legend-game-directory' ); ?></h2><ul><?php foreach ( (array) get_post_meta( $id, '_lgd_pros', true ) as $item ) : ?><li><?php echo esc_html( $item ); ?></li><?php endforeach; ?></ul></div><div class="lgd-panel"><h2><?php esc_html_e( 'Cons', 'legend-game-directory' ); ?></h2><ul><?php foreach ( (array) get_post_meta( $id, '_lgd_cons', true ) as $item ) : ?><li><?php echo esc_html( $item ); ?></li><?php endforeach; ?></ul></div></section>
		<?php $screens = (array) get_post_meta( $id, '_lgd_official_screenshots', true ); if ( $screens ) : ?><section class="lgd-section"><h2><?php esc_html_e( 'Official Screenshots', 'legend-game-directory' ); ?></h2><div class="lgd-grid"><?php foreach ( $screens as $screen ) : ?><figure class="lgd-card"><img loading="lazy" src="<?php echo esc_url( $screen ); ?>" alt="<?php echo esc_attr( sprintf( __( 'Official screenshot for %s', 'legend-game-directory' ), get_the_title() ) ); ?>"></figure><?php endforeach; ?></div></section><?php endif; ?>
		<section class="lgd-section lgd-two-col"><div class="lgd-panel"><h2><?php esc_html_e( 'Community Review', 'legend-game-directory' ); ?></h2><?php echo do_shortcode( '[lgd_review_form game_id="' . $id . '"]' ); ?></div><div class="lgd-panel"><h2><?php esc_html_e( 'Sources and Freshness', 'legend-game-directory' ); ?></h2><?php echo do_shortcode( '[lgd_sources game_id="' . $id . '"]' ); ?></div></section>
		<section class="lgd-section"><h2><?php esc_html_e( 'Similar Games', 'legend-game-directory' ); ?></h2><?php $genres = wp_get_post_terms( $id, 'game_genre', array( 'fields' => 'slugs' ) ); echo do_shortcode( '[lgd_game_grid limit="3" genre="' . esc_attr( isset( $genres[0] ) ? $genres[0] : '' ) . '"]' ); ?></section>
		<section class="lgd-section lgd-panel"><h2><?php esc_html_e( 'Report Incorrect Information', 'legend-game-directory' ); ?></h2><?php echo do_shortcode( '[lgd_report_game game_id="' . $id . '"]' ); ?></section>
	</div>
</main>
<?php get_footer(); ?>
